### ISSUE TITLE
Uncaught (in promise) RuntimeError: unreachable executed

### ISSUE THREAD

**Issue by bryan824** [silkenweb/ssr-example#1]
Thank you for this particular example to showcase SSR. I was migrating my code today, but it seems like it is broken in the latest code somehow.

This can be reproduced if we change the `app` function in [`packages/app/src/lib.rs`](https://github.com/silkenweb/ssr-example/blob/main/packages/app/src/lib.rs) to:
```rust
pub fn app<D:Dom>() -> Div<D> {
    let count = Mutable::new(0);
    let count_text = count.signal().map(|i| format!("{i}"));
    let inc = move |_, _| {
        count.replace_with(|i| *i + 1);
    };

    div()
        .child(button().on_click(inc).text("+"))
        .child(p().text(Sig(count_text)))
}
```

It works fine in this [commit](https://github.com/silkenweb/ssr-example/commit/4d299993e2be3aa84028ad5c348dcdb8f155f19c) though.

**Comment by bryan824** [comment]
In the latest version, it turns out it has to attach `.id("app")` to the `Div`.

**Comment by simon-bourne** [comment]
Glad you got this sorted by yourself. I assume you're aware of the `console_error_panic_hook` crate, which would log a more friendly error. Anyway, I've opened silkenweb/silkenweb#43 to try and improve the error message situation.

**Comment by bryan824** [comment]
yes. I have always thought that is an optional package until now. The SSR works pretty well in the latest commit of silkenweb. Just had to apply `sync_scope`.
